// ./scripts/genStudentOrgs/index.ts
//
// Generate student organization typescript array file.

// Local schema and util imports.
import { RawStudentOrgSchema } from "@scripts/genStudentOrgs/RawStudentOrg";
import outFileHeader from "@scripts/genStudentOrgs/outFileHeader";
import sanitizeStudentOrgs from "@scripts/genStudentOrgs/sanitizeStudentOrgs";
import csv2TS, { type CSV2TSOptions } from "@scripts/utils/csv2TS";
import { StudentOrgSchema } from "@src/schemas/StudentOrg";

export const options: CSV2TSOptions =
  // biome-ignore format: added alignment for clarity.
  {
    inFilePath      : "data/allStudentOrgs08292024.csv",
    inFileCSVHeaders: ["name", "purposeStatement", "affiliation"],
    inFileSchema    : RawStudentOrgSchema,
    middleFunction  : sanitizeStudentOrgs,
    outFilePath     : "src/autoGenerated/latestAllStudentOrgs.ts",
    outFileHeader   : outFileHeader,
    outFileFooter   : "",
    outFileSchema   : StudentOrgSchema,
};

export default async function genStudentOrgs(): Promise<void> {
  try {
    await csv2TS(options);
    console.log(
      `\x1b[36m[${genStudentOrgs.name}]\x1b[0m \x1b[32mSuccess\x1b[0m!!\n`,
    );
  } catch (error) {
    console.error(
      `[${genStudentOrgs.name}] Error: ${JSON.stringify(error)}.\n`,
    );
  }
}

// TESTING ONLY!! --------------------------------------------------------------
// Enable script to run standalone, comment out when done.
// genStudentOrgs();
