// ./scripts/genUndergradMajors/index.ts
//
// Generate undergrad majors typescript array file.

// Local schema and util imports.
import { RawUndergradMajorSchema } from "@scripts/genUndergradMajors/RawUndergradMajor";
import outFileHeader from "@scripts/genUndergradMajors/outFileHeader";
import sanitizeUndergradMajors from "@scripts/genUndergradMajors/sanitizeUndergradMajors";
import csv2TS, { type CSV2TSOptions } from "@scripts/utils/csv2TS";
import { UndergradMajorSchema } from "@src/schemas/UndergradMajor";

export const options: CSV2TSOptions =
  // biome-ignore format: added alignment for clarity.
  {
    inFilePath      : "data/allUndergradMajors08292024.csv",
    inFileCSVHeaders: ["major", "degree", "campus", "college"],
    inFileSchema    : RawUndergradMajorSchema,
    middleFunction  : sanitizeUndergradMajors,
    outFilePath     : "src/autoGenerated/latestAllUndergradMajors.ts",
    outFileHeader   : outFileHeader,
    outFileFooter   : "",
    outFileSchema   : UndergradMajorSchema,
};

export default async function genUndergradMajors(): Promise<void> {
  try {
    await csv2TS(options);
    console.log(
      `\x1b[36m[${genUndergradMajors.name}]\x1b[0m \x1b[32mSuccess\x1b[0m!!\n`,
    );
  } catch (error) {
    console.error(
      `[${genUndergradMajors.name}] Error: ${JSON.stringify(error)}.\n`,
    );
  }
}

// TESTING ONLY!! --------------------------------------------------------------
// Enable script to run standalone, comment out when done.
// genUndergradMajors();
