// ./scripts/genUndergradMajors/outFileHeader.ts
//
// Header for `./src/autoGenerated/latestAllUndergradMajors.ts`
// used in `./scripts/genUndergradMajors/index.ts`.

const outFileHeader: string = `// ./src/autoGenerated/latestAllUndergradMajors.ts
//
// AUTO-GENERATED on ${new Date().toISOString()}. DO NOT MODIFY.
// For details see "./scripts/genUndergradMajors/".

// Type imports.
import type { UndergradMajor } from "@src/schemas/UndergradMajor";

export const latestAllUndergradMajors: UndergradMajor[] =\n`;

export default outFileHeader;
