// ./src/autoGenerated/allUndergradMajorsAndDegrees.ts
//
// AUTO-GENERATED FILE. DO NOT MODIFY.
// For details see ./scripts/genAllUndergradMajorsAndDegrees.ts

// Type imports.
import type { Major } from "@src/osu";

export const allUndergradMajorsAndDegrees: Major[] =
[
  {
    "major": "Accounting",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Actuarial Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Aerospace Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "African American and African Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Agribusiness",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agribusiness and Applied Economics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agricultural Communication",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agricultural Communication",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agricultural Systems Management",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agricultural Systems Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agriculture, Exploring",
    "degree": null,
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agriscience Education",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agriscience Education",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Agronomy",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Ancient History and Classics",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Animal Sciences",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Animal Sciences",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Anthropological Sciences",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Anthropology",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Arabic",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Architecture",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Architecture"
  },
  {
    "major": "Art",
    "degree": "BA, BFA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Art Education",
    "degree": null,
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Arts and Sciences, Undecided",
    "degree": null,
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Arts Management",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Astronomy and Astrophysics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Atmospheric Sciences",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Aviation",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Aviation Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Biochemical Sciences",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Biochemistry",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Biology",
    "degree": "BS, BA",
    "campus": "Columbus, Lima, Marion",
    "college": "Arts and Sciences"
  },
  {
    "major": "Biomedical Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Biomedical Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Medicine"
  },
  {
    "major": "Business Administration, Undecided",
    "degree": null,
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Business Management",
    "degree": "BS",
    "campus": "Lima, Marion, Mansfield, Newark",
    "college": "Business"
  },
  {
    "major": "Business Management",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Chemical Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Chemistry",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Child and Youth Studies",
    "degree": "BS",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Chinese",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "City and Regional Planning",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Architecture"
  },
  {
    "major": "Civil Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Classics",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Communication",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Community Leadership",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Community Leadership",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Comparative Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Computer and Information Science",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Computer Science and Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Construction Management",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Construction Systems Management",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Construction Systems Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Consumer and Family Financial Services",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Criminology and Criminal Justice Studies",
    "degree": "BA",
    "campus": "Columbus, Marion, Mansfield",
    "college": "Arts and Sciences"
  },
  {
    "major": "Crop Management and Soil Conservation",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Culinary Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Dairy Cattle Production and Management",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Dance",
    "degree": "BFA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Data Analytics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Dental Hygiene",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Dental Hygiene"
  },
  {
    "major": "Dental Hygiene (baccalaureate completion program)",
    "degree": "BS",
    "campus": "Columbus, Lima",
    "college": "Dental Hygiene"
  },
  {
    "major": "Earth Sciences",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Economics",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Economics – Business",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Education – Integrated Language Arts/English Education",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Education – Middle Childhood Education",
    "degree": "BS",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Education – Primary Education",
    "degree": "BS",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Education – Science and Mathematics Education",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Education – Special Education",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Education – Teaching English to Speakers of Other Languages",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Education – Technical Education and Training",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Education – World Language Education",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Electrical and Computer Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Engineering Physics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Engineering Technology",
    "degree": "BS",
    "campus": "Lima, Marion, Mansfield, Newark",
    "college": "Engineering"
  },
  {
    "major": "English",
    "degree": "BA",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Arts and Sciences"
  },
  {
    "major": "Entomology",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Environment and Natural Resources",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Environment and Natural Resources, Undecided",
    "degree": null,
    "campus": "Columbus",
    "college": "Environment and Natural Resources"
  },
  {
    "major": "Environment, Economy, Development and Sustainability",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Environment and Natural Resources"
  },
  {
    "major": "Environmental Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Environmental Policy and Decision Making",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Environment and Natural Resources"
  },
  {
    "major": "Environmental Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Environment and Natural Resources"
  },
  {
    "major": "Evolution and Ecology",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Exercise Science Education",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Fashion and Retail Studies",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Film Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Finance",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Food Business Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Food Science and Technology",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Food, Agricultural and Biological Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Forensic Anthropology",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Forestry, Fisheries and Wildlife",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Environment and Natural Resources"
  },
  {
    "major": "French",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "French and Francophone Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Geographic Information Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Geography",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "German",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Greenhouse and Nursery Management",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Health and Rehabilitation Sciences, Undecided",
    "degree": null,
    "campus": "Columbus",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Health and Wellness",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Nursing"
  },
  {
    "major": "Health Information Management and Systems",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Health Promotion, Nutrition and Exercise Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Health Sciences",
    "degree": "BS",
    "campus": "Columbus, Lima",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Hebrew and Jewish Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "History",
    "degree": "BA",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Arts and Sciences"
  },
  {
    "major": "History of Art",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Horse Production and Management",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Horticultural Science",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Hospitality Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Human Development and Family Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Human Nutrition",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Human Resources",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Hydraulic Power and Motion Control",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Hydraulic Service and Repair",
    "degree": null,
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Industrial and Systems Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Industrial Design",
    "degree": "BSD",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Information Systems",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Insurance",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Integrated Major in Mathematics and English",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Interior Design",
    "degree": "BSD",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "International Business",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "International Studies",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Islamic Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Italian",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Italian Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Japanese",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Journalism",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Korean",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Landscape Architecture",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Architecture"
  },
  {
    "major": "Landscape Horticulture",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Linguistics",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Livestock Production and Management",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Logistics Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Marketing",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Materials Science and Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Mathematics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Mechanical Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Medical Anthropology",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Medical Laboratory Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Medieval and Renaissance Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Microbiology",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Modern Greek",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Molecular Genetics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Moving-Image Production",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Composition",
    "degree": "BM",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Education",
    "degree": "BME",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Jazz Studies",
    "degree": "BM",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Musicology",
    "degree": "BM",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Performance (orchestral instruments)",
    "degree": "BM",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Performance (piano)",
    "degree": "BM",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Performance (voice)",
    "degree": "BM",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Music – Theory",
    "degree": "BM",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Natural Resource Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Environment and Natural Resources"
  },
  {
    "major": "Neuroscience",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Nursing",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Nursing"
  },
  {
    "major": "Nursing (RN to BSN)",
    "degree": "BS",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Nursing"
  },
  {
    "major": "Occupational Therapy",
    "degree": null,
    "campus": "Columbus",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Operations Management",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Pharmaceutical Sciences",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Pharmacy"
  },
  {
    "major": "Philosophy",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Philosophy, Politics and Economics",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Physical Therapy",
    "degree": null,
    "campus": "Columbus",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Physics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Plant Pathology",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Political Science",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Portuguese",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Power Equipment",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Pre-Dentistry",
    "degree": null,
    "campus": "Columbus",
    "college": "Pre-Professional"
  },
  {
    "major": "Pre-Law",
    "degree": null,
    "campus": "Columbus",
    "college": "Pre-Professional"
  },
  {
    "major": "Pre-Medicine",
    "degree": null,
    "campus": "Columbus",
    "college": "Pre-Professional"
  },
  {
    "major": "Pre-Optometry",
    "degree": null,
    "campus": "Columbus",
    "college": "Pre-Professional"
  },
  {
    "major": "Pre-Pharmacy",
    "degree": null,
    "campus": "Columbus",
    "college": "Pre-Professional"
  },
  {
    "major": "Pre-Veterinary Medicine",
    "degree": null,
    "campus": "Columbus",
    "college": "Pre-Professional"
  },
  {
    "major": "Professional Golf Management",
    "degree": null,
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Professional Golf Management 1 + 3",
    "degree": null,
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Psychology",
    "degree": "BS, BA",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Arts and Sciences"
  },
  {
    "major": "Public Health",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Public Health"
  },
  {
    "major": "Public Management, Leadership and Policy",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Public Affairs"
  },
  {
    "major": "Public Policy Analysis",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Public Affairs"
  },
  {
    "major": "Radiologic Sciences and Therapy",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Real Estate and Urban Analysis",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Business"
  },
  {
    "major": "Religious Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Respiratory Therapy",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Health and Rehabilitation Sciences"
  },
  {
    "major": "Romance Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Russian",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Social Sciences Air Transportation",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Social Work",
    "degree": "BS",
    "campus": "Columbus, Lima, Marion, Mansfield, Newark",
    "college": "Social Work"
  },
  {
    "major": "Sociology",
    "degree": "BS, BA",
    "campus": "Columbus, Mansfield",
    "college": "Arts and Sciences"
  },
  {
    "major": "Spanish",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Speech and Hearing Science",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Sport Industry",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Education and Human Ecology"
  },
  {
    "major": "Statistics",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Sustainable Agriculture",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Sustainable Agriculture",
    "degree": "AS",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Sustainable Plant Systems",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "Theatre",
    "degree": "BA",
    "campus": "Columbus, Lima",
    "college": "Arts and Sciences"
  },
  {
    "major": "Turfgrass Management",
    "degree": "AA",
    "campus": "ATI Wooster",
    "college": "Food, Agricultural and Environmental Sciences"
  },
  {
    "major": "University Exploration – Arts, Innovation and Creativity Exploration",
    "degree": null,
    "campus": "Columbus",
    "college": "University Exploration"
  },
  {
    "major": "University Exploration – Behavior, Culture and Context Exploration",
    "degree": null,
    "campus": "Columbus",
    "college": "University Exploration"
  },
  {
    "major": "University Exploration – Education and Public Service Exploration",
    "degree": null,
    "campus": "Columbus",
    "college": "University Exploration"
  },
  {
    "major": "University Exploration – Health and Human Services Exploration",
    "degree": null,
    "campus": "Columbus",
    "college": "University Exploration"
  },
  {
    "major": "University Exploration – Management and Industry Exploration",
    "degree": null,
    "campus": "Columbus",
    "college": "University Exploration"
  },
  {
    "major": "University Exploration – Science, Technology and Environment Exploration",
    "degree": null,
    "campus": "Columbus",
    "college": "University Exploration"
  },
  {
    "major": "University Exploration – Undecided/Exploring",
    "degree": null,
    "campus": "Columbus",
    "college": "University Exploration"
  },
  {
    "major": "Vision Science",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Visual Communication Design",
    "degree": "BSD",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Welding Engineering",
    "degree": "BS",
    "campus": "Columbus",
    "college": "Engineering"
  },
  {
    "major": "Women's, Gender and Sexuality Studies",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "World Literatures",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "World Politics",
    "degree": "BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  },
  {
    "major": "Zoology",
    "degree": "BS, BA",
    "campus": "Columbus",
    "college": "Arts and Sciences"
  }
];
