// ./src/studentOrgs/getStudentOrgs.ts
//
// Utility functions to retrieve student organization data.

// Local type, constants, and utility imports.
import { latestAllStudentOrgs } from "@src/autoGenerated/latestAllStudentOrgs";
import type { StudentOrg } from "@src/schemas/StudentOrg";

export function getStudentOrgs(): StudentOrg[] {
  return latestAllStudentOrgs;
}

// TODO: Implement async version with option to use cache.
// export function getStudentOrgsAsync(): Promise<StudentOrg[]> {
//   return Promise.resolve(getStudentOrgs());
// }
