// ./scripts/genAllUndergradMajorsAndDegrees.ts
//
// Generate undergrad majors and degrees typescript array file.

// Zod essential imports.
import { type ZodSchema, z } from "zod";

// Local utils imports.
import csv2TS, {
  type csv2TSOptions,
  DEFAULT_HEADER,
} from "@scripts/utils/csv2TS.js";

export const rawUndergradMajor: ZodSchema = z.object(
  // biome-ignore format: added alignment for clarity.
  {
    major  : z.string().min(1),
    degree : z.string(),
    campus : z.string(),
    college: z.string(),
  },
);
export type rawUndergradMajor = z.infer<typeof rawUndergradMajor>;

export const undergradMajor: ZodSchema = z.object(
  // biome-ignore format: added alignment for clarity.
  {
    major  : z.string().min(1),
    degree : z.nullable(z.string().min(1)),
    campus : z.nullable(z.string().min(1)),
    college: z.nullable(z.string().min(1)),
  },
);
export type undergradMajor = z.infer<typeof undergradMajor>;

export function sanitizeUndergradMajorsAndDegrees(
  data: rawUndergradMajor[],
): undergradMajor[] {
  return data.map((dataPoint) => {
    const degree = dataPoint.degree;
    const campus = dataPoint.campus;
    const college = dataPoint.college;
    return {
      ...dataPoint,
      degree: degree === "" ? null : degree,
      campus: campus === "" ? null : campus,
      college: college === "" ? null : college,
    };
  });
}

export const allUndergradMajorsAndDegreesOptions: csv2TSOptions =
  // biome-ignore format: added alignment for clarity.
  {
    inFilePath      : "data/allUndergradMajorsAndDegrees062924.csv",
    inFileCSVHeaders: ["major", "degree", "campus", "college"],
    inFileSchema    : rawUndergradMajor,
    middleFunction  : sanitizeUndergradMajorsAndDegrees,
    outFilePath     : "src/autoGenerated/allUndergradMajorsAndDegrees.ts",
    outFileHeader   : DEFAULT_HEADER,
    outFileArrayName: "allUndergradMajorsAndDegrees",
    outFileSchema   : undergradMajor
};

// Main function to convert allUndergradMajorsAndDegrees csv to ts array file.
export default async function genAllUndergradMajorsAndDegrees(): Promise<void> {
  await csv2TS(allUndergradMajorsAndDegreesOptions);
}
