// ./scripts/genAllStudentOrgs.ts
//
// Generate student organization typescript array file.

// Zod essential imports.
import { type ZodSchema, z } from "zod";

// Local utils imports.
import csv2TS, {
  DEFAULT_HEADER,
  type csv2TSOptions,
} from "@scripts/utils/csv2TS.js";

export const studentOrg: ZodSchema = z.object(
  // biome-ignore format: added alignment for clarity.
  {
    name            : z.string().min(1),
    purposeStatement: z.string().min(1),
    affiliation     : z.string().min(1),
  },
);

export const allStudentOrgsOptions: csv2TSOptions =
  // biome-ignore format: added alignment for clarity.
  {
    inFilePath      : "data/allStudentOrgs062824.csv",
    inFileCSVHeaders: ["name", "purposeStatement", "affiliation"],
    outFilePath     : "src/autoGenerated/allStudentOrgs.ts",
    outFileHeader   : DEFAULT_HEADER,
    outFileArrayName: "allStudentOrgs",
    schema          : studentOrg,
};

export default async function genAllStudentOrgs(): Promise<void> {
  await csv2TS(allStudentOrgsOptions);
}
