// ./scripts/genAllUndergradMajorsAndDegrees.ts
//
// Generate undergrad majors and degrees typescript array file.

// Zod essential imports.
import { type ZodSchema, z } from "zod";

// Local utils imports.
import csv2TS, { type csv2TSOptions } from "@scripts/utils/csv2TS";

// Define raw data schema for input csv validation. ----------------------------
export const rawUndergradMajor: ZodSchema = z.object(
  // biome-ignore format: added alignment for clarity.
  {
    major  : z.string().min(1),
    degree : z.string(),
    campus : z.string(),
    college: z.string(),
  },
);
export type rawUndergradMajor = z.infer<typeof rawUndergradMajor>;

// Define undergrad major schema for output ts validation. ---------------------
export const undergradMajor: ZodSchema = z.object(
  // biome-ignore format: added alignment for clarity.
  {
    major  : z.string().min(1),
    degree : z.nullable(z.string().min(1)),
    campus : z.nullable(z.string().min(1)),
    college: z.nullable(z.string().min(1)),
  },
);
export type undergradMajor = z.infer<typeof undergradMajor>;

// Define middle fn to sanitize raw data into undergrad major data. ------------
export function sanitizeUndergradMajorsAndDegrees(
  data: rawUndergradMajor[],
): undergradMajor[] {
  return data.map((dataPoint) => {
    const degree = dataPoint.degree;
    const campus = dataPoint.campus;
    const college = dataPoint.college;
    return {
      ...dataPoint,
      degree: degree === "" ? null : degree,
      campus: campus === "" ? null : campus,
      college: college === "" ? null : college,
    };
  });
}

// Define allUndergradMajorsAndDegrees header and footer. ----------------------
export const allUndergradMajorsAndDegreesHeader: string = `// ./src/autoGenerated/allUndergradMajorsAndDegrees.ts
//
// AUTO-GENERATED FILE. DO NOT MODIFY.
// For details see ./scripts/genAllUndergradMajorsAndDegrees.ts

// Type imports.
import type { Major } from "@src/osu";

export const allUndergradMajorsAndDegrees: Major[] =\n`;

// Set up options for allUndergradMajorsAndDegrees conversion. -----------------
export const allUndergradMajorsAndDegreesOptions: csv2TSOptions =
  // biome-ignore format: added alignment for clarity.
  {
    inFilePath      : "data/allUndergradMajorsAndDegrees062924.csv",
    inFileCSVHeaders: ["major", "degree", "campus", "college"],
    inFileSchema    : rawUndergradMajor,
    middleFunction  : sanitizeUndergradMajorsAndDegrees,
    outFilePath     : "src/autoGenerated/allUndergradMajorsAndDegrees.ts",
    outFileHeader   : allUndergradMajorsAndDegreesHeader,
    outFileFooter   : "",
    outFileSchema   : undergradMajor
};

// Main conversion function. ---------------------------------------------------
export default async function genAllUndergradMajorsAndDegrees(): Promise<void> {
  await csv2TS(allUndergradMajorsAndDegreesOptions);
}

// Enable script to run standalone. --------------------------------------------
// genAllUndergradMajorsAndDegrees();
