// ./scripts/genAllUndergradMajorsAndDegrees.ts
//
// Generate undergrad majors and degrees typescript array file.

// Zod essential imports.
import { type ZodSchema, z } from "zod";

// Local utils imports.
import csv2TS, {
  type csv2TSOptions,
  DEFAULT_HEADER,
} from "@scripts/utils/csv2TS.js";

const undergradMajor: ZodSchema = z.object(
  // biome-ignore format: added alignment for clarity.
  {
    major  : z.string().min(1),
    degree : z.string(),
    campus : z.string(),
    college: z.string(),
  },
);

export const allUndergradMajorsAndDegreesOptions: csv2TSOptions =
  // biome-ignore format: added alignment for clarity.
  {
    inFilePath      : "data/allUndergradMajorsAndDegrees062924.csv",
    inFileCSVHeaders: ["major", "degree", "campus", "college"],
    outFilePath     : "src/autoGenerated/allUndergradMajorsAndDegrees.ts",
    outFileHeader   : DEFAULT_HEADER,
    outFileArrayName: "allUndergradMajorsAndDegrees",
    schema          : undergradMajor,
};

export default async function genAllUndergradMajorsAndDegrees(): Promise<void> {
  await csv2TS(allUndergradMajorsAndDegreesOptions);
}
