// ./src/osu.test.ts
//
// Unit and integration tests for the osu namespace and utilities.

// Vitest essential imports.
import { describe, expect, it } from "vitest";

// Local class, constant, and util imports.
import { studentOrg } from "@scripts/genAllStudentOrgs.js";
import { undergradMajor } from "@scripts/genAllUndergradMajorsAndDegrees.js";
import allStudentOrgs from "@src/autoGenerated/allStudentOrgs.js";
import allUndergradMajorsAndDegrees from "@src/autoGenerated/allUndergradMajorsAndDegrees.js";

// Testing module imports.
import osu from "@src/osu.js";

// The osu namespace test suite.
describe("The osu namespace", () => {
  it("has an undergrad sub-namespace", () => {
    expect(osu.undergrad).toBeDefined();
  });

  it("has a undergrad.majors constant", () => {
    expect(osu.undergrad.majors).toBeDefined();
    expect(osu.undergrad.majors).toStrictEqual(allUndergradMajorsAndDegrees);
    expect(osu.undergrad.majors).toMatchSnapshot();
    undergradMajor.array().parse(osu.undergrad.majors);
  });

  it("has a studentOrgs constant", () => {
    expect(osu.studentOrgs).toBeDefined();
    expect(osu.studentOrgs).toStrictEqual(allStudentOrgs);
    expect(osu.studentOrgs).toMatchSnapshot();
    studentOrg.array().parse(osu.studentOrgs);
  });
});
