// ./src/osu.ts
//
// The osu (lower-cased for accessibility) namespace,
// encapsulates OSU-related data services.

// Local utils and contant imports.
import allStudentOrgs from "@src/autoGenerated/allStudentOrgs";
import allUndergradMajorsAndDegrees from "@src/autoGenerated/allUndergradMajorsAndDegrees";

// OSU namespace, class, function, and constant etc. definitions.
namespace osu {
  export namespace undergrad {
    export const majors = allUndergradMajorsAndDegrees;
  }

  export const studentOrgs = allStudentOrgs;
}
export default osu;
