// ./src/osu.ts
//
// The osu (lower-cased for accessibility) namespace,
// encapsulates OSU-related data services.

// Local utils and contant imports.
import allStudentOrgs from "@src/autoGenerated/allStudentOrgs";
import allUndergradMajorsAndDegrees from "@src/autoGenerated/allUndergradMajorsAndDegrees";

export namespace osu {

  // OSU Undergraduate namespace. ----------------------------------------------
  export namespace undergrad {

    /**
     * A list of all undergraduate majors and degrees.
     * 
     * @type {osu.undergrad.Major[]}
     * 
     * @memberof osu.undergrad
     */
    export const majors: Major[] = allUndergradMajorsAndDegrees;
  }
  
  // OSU Student Organizations array. ------------------------------------------
  /**
   * A list of all student organizations.
   * 
   * @type {osu.StudentOrg[]}
   * 
   * @memberof osu
   */
  export const studentOrgs: StudentOrg[] = allStudentOrgs;
}

// OSU-related types. ----------------------------------------------------------
/**
 * Represents an undergraduate major.
 * 
 * @typedef {Object} Major
 * 
 * @property {string} major - The name of the major.
 * @property {string|null} degree - The degree associated with the major, or null if not applicable.
 * @property {string} campus - The campus where the major is offered.
 * @property {string} college - The college that offers the major.
 */
export interface Major {
  major  : string;
  degree : string | null;
  campus : string;
  college: string;
}

/**
 * Represents a student organization.
 * 
 * @typedef {Object} StudentOrg
 * 
 * @property {string} name - The name of the student organization.
 * @property {string} purposeStatement - A paragraph about the organization's purpose.
 * @property {string[]} affiliation - Includes campus, category, mission, etc.
 */
 export interface StudentOrg {
  name            : string;
  purposeStatement: string;
  affiliation     : string[];
}
